Chore/sc 519/upgrade swr to 1 0
makerdao/governance-portal-v2 pull request #244
Opened 2021-11-11 14:21 UTC by adamgoth

### Link to Clubhouse story

https://app.shortcut.com/dux-makerdao/story/519/upgrade-swr-to-1-0

### What does this PR do?

Upgrades to SWR 1.0

Reduces default polling interval

Cuts down on unnecessary calls

Adds mutations (revalidation) where necessary

### Steps for testing:

Check all the pages of the app. Send tests transactions. Look for anything funky.

### Any additional helpful information?:

Reducing infura calls will be handled in a separate PR

### Add a GIF:
![](https://media.giphy.com/media/RMwcpN4Q3ZN4A4TaLL/giphy.gif)

2021-11-17 14:52 UTC, rafinskipg requested changes
So it seems on the delegates page, if you freshload, it does not load the MKR delegated, but if you switch focus ( change to other app or tab) it does refresh the balances

2021-11-17 14:52 UTC, rafinskipg commented on modules/executive/hooks/useSpellData.ts
> +    mutate
nice

2021-11-18 19:57 UTC, adamgoth commented
> So it seems on the delegates page, if you freshload, it does not load the MKR delegated, but if you switch focus ( change to other app or tab) it does refresh the balances

Nice catch. Should be fixed now  🔨

2021-11-18 19:58 UTC, adamgoth commented on lib/hooks/useDelegateAddressMap.ts
> +    refreshInterval: 0
Exactly

2021-11-18 20:01 UTC, adamgoth commented on modules/delegates/components/modals/DelegateModal.tsx
> +        mutateMkrStaked();
Not on modal close. When we broadcast the tx, we track it through dai.js's transaction manager (through `trackTranscation`). That tracking function provides hooks for when the tx status changes. So as soon as we detect that the tx was mined, that's when those functions trigger.

2021-11-18 20:02 UTC, adamgoth commented on modules/executive/hooks/useSpellData.ts
> +    mutate
![](https://media.giphy.com/media/QEYYlJqOaEhXrjTrOH/giphy.gif)

2021-11-19 15:23 UTC, rafinskipg approved these changes

2021-11-19 15:37 UTC, merged