Gasless mainnet
makerdao/governance-portal-v2 pull request #650
Opened 2022-09-21 12:37 UTC by tyler17

What does this PR do?
Gasless voting on Mainnet
### Steps for testing:
Add the necessary .env variables (DEFENDER_API_KEY_PROD, DEFENDER_API_SECRET_PROD, NEXT_PUBLIC_ALCHEMY_ARBITRUM_KEY) values can be found in vercel or our password manager. Acquire .1 MKR. Vote on mainnet.

### Screenshot
<img width="800" alt="Screen Shot 2022-09-21 at 10 05 48 AM" src="https://user-images.githubusercontent.com/3388550/191505267-a57bf722-a67f-4e9c-9a17-4f4df4e0808c.png">

Example of successful mainnet transcaction from relayer: https://arbiscan.io/tx/0xdab110a94977bb4ada4e1e202fae9b5741d337bfc9d6d5e75c741bf7a8ca9ec9

2022-09-21 14:02 UTC, rafinskipg requested changes
LGTM but i have a question regarding the NEXT_PUBLIC RPC provider for arbitrum, 

aren't we using the provider only on the server side? In that case it does not need to use NEXT_PUBLIC

2022-09-21 16:21 UTC, tyler17 commented on lib/config.ts
> +  DEFENDER_API_SECRET_PROD: process.env.DEFENDER_API_SECRET_PROD || '',
Yeah I'll do that, that's more clear

2022-09-21 16:22 UTC, tyler17 commented
> LGTM but i have a question regarding the NEXT_PUBLIC RPC provider for arbitrum,
> 
> aren't we using the provider only on the server side? In that case it does not need to use NEXT_PUBLIC

Actually we do use it on the frontend, when we generate the signature we need to read the nonce from the arbitrum polling contract

2022-09-22 10:14 UTC, rafinskipg approved these changes

2022-09-22 12:59 UTC, merged