handle errors from vote API as well as RPC errors from wallet
makerdao/governance-portal-v2 pull request #653
Opened 2022-09-22 22:24 UTC by b-pmcg

### Link to Shortcut ticket:
[1773]
[1776]

### What does this PR do?
Handle errors that come from our API and parse them for the error message to display. Also handle RPC and provider related errors with [eth-rpc-errors](https://github.com/MetaMask/eth-rpc-errors) lib

2022-09-25 16:14 UTC, tyler17 approved these changes
Looks like some tests may need to be updated, but otherwise looks good

2022-09-26 07:40 UTC, rafinskipg requested changes
The appi should return a error object,
```
{
  error: 'Something'
}
```

At least that is how is handled on the rest of apy endpoints

2022-09-27 14:11 UTC, rafinskipg approved these changes

2022-09-28 08:53 UTC, adamgoth approved these changes

2022-09-28 09:18 UTC, merged